### ISSUE TITLE
更改底栏样式。

### ISSUE THREAD

**Issue by taozina0587** [UserZYF/green-elephant#2]
兄弟，你的主题太棒了！ 你能帮助我吗？ 当我们应用 13 种文本样式中的一种时，如何增加出现在字母下方的底栏？

![image](https://user-images.githubusercontent.com/90691302/167940669-65800cec-bec5-44a6-afa2-c7a721f3fb22.png)

**Comment by UserZYF** [comment]
首先，找到下面文件路径，打开下面的文件
white-elephant/style/03-inline-span/strong-morestyle.css
在里边加入下面的代码
strong[style="background-color: var(--b3-font-background9);"] {
    border-bottom: 0.1em solid black;
}
你可以将其中的数字9修改为9-12中的任何数字，也可以修改下面的black颜色
然后保存这个css，最后再打开theme.css保存即可

**Comment by taozina0587** [comment]
Thanks for all.

**Comment by taozina0587** [comment]
@UserZYF 你能添加另一個文本效果嗎？ 我通過思源學習，下面這個文字效果對我來說太棒了！

![image](https://user-images.githubusercontent.com/90691302/168083120-b66adee5-e225-49e6-a90b-fd7d48864cc9.png)

Link for css code: https://alvarotrigo.com/blog/css-highlight-text/

**Comment by UserZYF** [comment]
我可以试一试，不过最近我有些忙，这可能要等上几个星期
